data_path: '../datasets/train'
eval_data_path: '../datasets/val'
batch_size: 2
batch_size_eval: 2
num_workers: 5

corruptions: None
eval_corruptions: None
n_frames: 8
img_size: 192

epochs: 100
eval_freq: 200
save_weight_freq: 5
output_dir: 'results/baseline'
device: 'cuda'

lr: 0.001
loss_fn: 'midas'

log_wandb: True
wandb_project: 'multiview-robustness-cs-503'
wandb_entity: 'aav'
wandb_run_name: 'baseline'
