data_path: '../datasets/train'
eval_data_path: '../datasets/val'
batch_size: 1
batch_size_eval: 1
num_workers: 5

corruptions: None
eval_corruptions: None
n_frames: 10
img_size: 384

epochs: 100
eval_freq: 200
save_weight_freq: 20
output_dir: 'results/multiview'
device: 'cuda'

lr: 0.00001
loss_fn: 'midas'

log_wandb: True
wandb_project: 'multiview-robustness-cs-503'
wandb_entity: 'aav'
wandb_run_name: 'multiview'
