data_path: '/scratch/izar/aasadi/dataset/data/train'
eval_data_path: '/scratch/izar/aasadi/dataset/data/val'
batch_size: 2
batch_size_eval: 1
num_workers: 5

corruptions: None
eval_corruptions: None
n_frames: 4
img_size: 384
num_seq_knowledge_source: 300
small: True

epochs: 100
eval_freq: 500
save_weight_freq: 20
output_dir: 'results/multiview-ks300'
device: 'cuda:0'

lr: 0.00001
loss_fn: 'midas'

log_wandb: True
wandb_project: 'multiview-robustness-cs-503'
wandb_entity: 'aav'
wandb_run_name: 'multiview-ks300'
