data_path: '/scratch/izar/aasadi/dataset/data/train'
eval_data_path: '/scratch/izar/aasadi/dataset/data/val'
batch_size: 2
batch_size_eval: 1
num_workers: 5

corruptions: None
eval_corruptions: None
n_frames: 4
img_size: 384
pos3d_encoding: False

epochs: 100
eval_freq: 500
save_weight_freq: 20
output_dir: 'results/multiview_no-pos3d'
device: 'cuda:0'

lr: 0.00001
loss_fn: 'midas'

log_wandb: True
wandb_project: 'multiview-robustness-cs-503'
wandb_entity: 'aav'
wandb_run_name: 'multiview_no-pos3d'
